$(document).ready(function(){
 	$('.slider-area.owl-carousel').owlCarousel({
	    loop:true,
	    nav:true,
	    responsiveClass:true,
	    responsive:{
	        0:{
	            items:1,
	            nav:true,
	        },
	        600:{
	            items:1,
	            nav:true,
	        },
	        1000:{
	            items:1,
	            nav:true,
	            loop:true,
	        }
	    }
	});
	$('.student.owl-carousel').owlCarousel({
	    loop:true,
	    nav:false,
	    loop:true,
	    dotted:true,
	    responsiveClass:true,
	    responsive:{
	        0:{
	            items:1,
	            items:1,
	            autoplay:true,
				autoplayTimeout:5000,
				autoplayHoverPause:true,
	        },
	        568:{
	            items:1,
	            autoplay:true,
				autoplayTimeout:5000,
				autoplayHoverPause:true,
	        },
	        568:{
	            items:1,
	        },
	        1000:{
	            items:1,
	        }
	    }
	});
	$('.teacher-details.owl-carousel').owlCarousel({
		items:4,
	    loop:true,
	    nav:true,
	    margin:30,
	    responsiveClass:true,
	    responsive:{
	        0:{
	            items:1,
	            items:1,
	            autoplay:true,
				autoplayTimeout:5000,
				autoplayHoverPause:true,
	        },
	        568:{
	            items:2,
	            autoplay:true,
				autoplayTimeout:5000,
				autoplayHoverPause:true,
	        },
	        768:{
			    items:3,
			    nav:true,
	        },
	        1000:{
	            items:4,
	        }
	    }
	});
	$('.news-item.owl-carousel').owlCarousel({
		items:3,
		margin:30,
		loop:true,
	    nav:true,
	    responsiveClass:true,
	    responsive:{
	        0:{
	            items:1,
	            autoplay:true,
				autoplayTimeout:1000,
				autoplayHoverPause:true,
	        },
	        568:{
	            items:2,
	            autoplay:true,
				autoplayTimeout:5000,
				autoplayHoverPause:true,
	        },
	        768:{
	            items:3,
	        },
	        1000:{
	            items:3,
	            nav:true,
	        }
	    }
	});
	
	
});